// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEAqQ5I3nIIsfnjCQEfn0WXsbwSIjbMM',
    appId: '1:1066368084845:web:825ecaf1a90f7b08e48864',
    messagingSenderId: '1066368084845',
    projectId: 'first-app-31632',
    authDomain: 'first-app-31632.firebaseapp.com',
    storageBucket: 'first-app-31632.appspot.com',
    measurementId: 'G-YVSYFLNTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2U_dEwvXCtmi2Ccvvwh8ODUoC_xqvefw',
    appId: '1:1066368084845:android:565f3498acb2ec66e48864',
    messagingSenderId: '1066368084845',
    projectId: 'first-app-31632',
    storageBucket: 'first-app-31632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvwOGBTqOnh4Y50X1hOTUCHFNEJM_wyuI',
    appId: '1:1066368084845:ios:9b889f5111d9d52de48864',
    messagingSenderId: '1066368084845',
    projectId: 'first-app-31632',
    storageBucket: 'first-app-31632.appspot.com',
    iosBundleId: 'com.example.doAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvwOGBTqOnh4Y50X1hOTUCHFNEJM_wyuI',
    appId: '1:1066368084845:ios:d00fb284b8606f6ae48864',
    messagingSenderId: '1066368084845',
    projectId: 'first-app-31632',
    storageBucket: 'first-app-31632.appspot.com',
    iosBundleId: 'com.example.doAn.RunnerTests',
  );
}
